version: '3'

services:
  nginx:
    image: brunomeloesilva/nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    networks:
      - my-net
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_started

  app:
    image: brunomeloesilva/app:latest
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    networks:
      - my-net
    tty: true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./node:/home/node/app
      - /home/node/app

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - my-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
networks:
  my-net:
    driver: bridge